version: '3.1'
services:
  oppia-app:
    build:
      context: ./
    container_name: oppia-app
    depends_on:
      - oppia-mariadb
    networks:
      - oppia
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ./.data/config/settings_secret.py:/home/oppia/django-oppia/oppiamobile/settings_secret.py
      - ./.data/media:/home/oppia/media
      - ./.data/static:/home/oppia/static
      - ./.data/upload:/home/oppia/upload

  oppia-mariadb:
    container_name: oppia-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: "oppia"
      MYSQL_USER: "oppia"
      MYSQL_PASSWORD: "oppia"
    image: mariadb:10
    networks:
      - oppia
    restart: unless-stopped
    volumes:
      - ./.data/mysql:/var/lib/mysql

networks:
  oppia:
    driver: bridge
    name: oppia
