name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull existing image for caching purposes
        run: docker pull ${{ github.repository }}:latest || true

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          cache-from: type=registry,ref=${{ github.repository }}:latest
          cache-to: type=inline
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ github.repository }}:${{ github.sha }}
            ${{ github.repository }}:latest
